import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "events-manage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>   
        <div className="bg-slate-500 font-bold p-4 text-4xl">
          <Link href="/" className="mx-4 ">Home</Link>
          <Link href="/frontend/new_event" className="mx-4">Nuevo Evento</Link>
          <Link href="/frontend/list_events" className="mx-4">Lista</Link>
          <Link href="/frontend/list_groups" className="mx-4">Grupos</Link>
        </div>


        {children}
      </body>
    </html>
  );
}
